const schemesData = [
  {
    id: 'ab',
    name: 'Ayushman Bharat (PM-JAY)',
    shortName: 'PM-JAY',
    icon: '🏥',
    color: '#2563EB',
    bgColor: '#EFF6FF',
    coverage: '₹5,00,000',
    coveragePeriod: 'per family / year',
    description: 'Provides free health coverage of up to ₹5 Lakhs per family per year for secondary and tertiary care hospitalization across public and private empaneled hospitals.',
    benefits: [
      'Up to ₹5 Lakh cashless treatment',
      'Covers 1,929+ medical procedures',
      'No cap on family size',
      'Pre & post hospitalization expenses covered',
      'All pre-existing diseases covered from day one',
    ],
    eligibility: {
      maxIncome: 300000,
      minAge: 0,
      maxAge: 120,
      description: 'Families identified based on SECC 2011 data or ration card holders in rural/urban areas.',
    },
    documents: [
      { name: 'Aadhaar Card', required: true },
      { name: 'Ration Card / SECC Data', required: true },
      { name: 'Family ID Proof', required: true },
      { name: 'Age Proof (Birth Certificate)', required: false },
      { name: 'Income Certificate', required: false },
    ],
    helpline: '14555',
    website: 'https://pmjay.gov.in',
  },
  {
    id: 'mj',
    name: 'MJPJAY (Maharashtra)',
    shortName: 'MJPJAY',
    icon: '🏛️',
    color: '#15803D',
    bgColor: '#F0FDF4',
    coverage: '₹1,50,000',
    coveragePeriod: 'per family / year',
    description: 'Mahatma Jyotirao Phule Jan Arogya Yojana provides cashless medical and surgical treatment to Below Poverty Line (BPL) and Above Poverty Line (APL) families in Maharashtra.',
    benefits: [
      'Covers 996 medical & surgical procedures',
      'Cashless treatment at network hospitals',
      'Follow-up treatment for 10 days post-discharge',
      'Transport allowance of ₹100-₹500',
      'Covers critical illnesses including cancer, renal, cardiac',
    ],
    eligibility: {
      maxIncome: 100000,
      minAge: 0,
      maxAge: 120,
      description: 'Yellow / Orange ration card holders in Maharashtra. Annual family income below ₹1 Lakh.',
    },
    documents: [
      { name: 'Yellow/Orange Ration Card', required: true },
      { name: 'Aadhaar Card', required: true },
      { name: 'Income Certificate', required: true },
      { name: 'Domicile Certificate', required: true },
      { name: 'Photograph (Passport size)', required: false },
    ],
    helpline: '155388',
    website: 'https://www.jeevandayee.gov.in',
  },
  {
    id: 'pmjjby',
    name: 'PM Jeevan Jyoti Bima Yojana',
    shortName: 'PMJJBY',
    icon: '🛡️',
    color: '#7C3AED',
    bgColor: '#F5F3FF',
    coverage: '₹2,00,000',
    coveragePeriod: 'life cover',
    description: 'A government-backed life insurance scheme offering life coverage of ₹2 Lakh at a nominal annual premium of just ₹436, auto-debited from the bank account.',
    benefits: [
      'Life cover of ₹2 Lakh on death due to any reason',
      'Annual premium of only ₹436',
      'Auto-debit from savings account',
      'Easy enrollment via bank or post office',
      'No medical examination required',
    ],
    eligibility: {
      maxIncome: 9999999,
      minAge: 18,
      maxAge: 50,
      description: 'Any Indian citizen aged 18-50 with a savings bank account. Premium auto-debited annually.',
    },
    documents: [
      { name: 'Savings Bank Account', required: true },
      { name: 'Aadhaar Card', required: true },
      { name: 'Age Proof', required: true },
      { name: 'Nomination Form', required: true },
    ],
    helpline: '1800-180-1111',
    website: 'https://jansuraksha.gov.in',
  },
];

export default schemesData;
